export const queryKeys = {
  organizations: ['organizations'] as const,
  organization: (id: string) => ['organizations', id] as const,
  profile: ['users', 'me'] as const,
  properties: (orgId: string) => ['orgs', orgId, 'properties'] as const,
  property: (orgId: string, id: string) => ['orgs', orgId, 'properties', id] as const,
  units: (orgId: string, propertyId: string) => ['orgs', orgId, 'properties', propertyId, 'units'] as const,
  buildings: (orgId: string, propertyId: string) => ['orgs', orgId, 'properties', propertyId, 'buildings'] as const,
  tenants: (orgId: string) => ['orgs', orgId, 'tenants'] as const,
  tenancies: (orgId: string) => ['orgs', orgId, 'tenancies'] as const,
  payments: (orgId: string) => ['orgs', orgId, 'payments'] as const,
  rentCharges: (orgId: string) => ['orgs', orgId, 'rent-charges'] as const,
  receipts: (orgId: string) => ['orgs', orgId, 'receipts'] as const,
  ledger: (orgId: string, tenancyId: string) => ['orgs', orgId, 'tenancies', tenancyId, 'ledger'] as const,
  maintenance: (orgId: string) => ['orgs', orgId, 'maintenance'] as const,
  conversations: (orgId: string) => ['orgs', orgId, 'conversations'] as const,
  announcements: (orgId: string) => ['orgs', orgId, 'announcements'] as const,
  inquiries: (orgId: string) => ['orgs', orgId, 'inquiries'] as const,
  notifications: ['notifications', 'me'] as const,
  notificationUnread: ['notifications', 'me', 'unread'] as const,
  subscription: (orgId: string) => ['orgs', orgId, 'subscription'] as const,
  limits: (orgId: string) => ['orgs', orgId, 'limits'] as const,
  listings: (params: Record<string, unknown>) => ['listings', params] as const,
  reports: {
    financial: (orgId: string) => ['orgs', orgId, 'reports', 'financial'] as const,
    occupancy: (orgId: string) => ['orgs', orgId, 'reports', 'occupancy'] as const,
    tenants: (orgId: string) => ['orgs', orgId, 'reports', 'tenants'] as const,
    maintenance: (orgId: string) => ['orgs', orgId, 'reports', 'maintenance'] as const,
  },
  analytics: (orgId: string, scope?: { propertyId?: string; unitTypeId?: string }) =>
    ['orgs', orgId, 'analytics', scope ?? 'portfolio'] as const,
  insights: (orgId: string, scope?: { propertyId?: string; unitTypeId?: string }) =>
    ['orgs', orgId, 'analytics', 'insights', scope ?? 'portfolio'] as const,
  plans: ['subscriptions', 'plans'] as const,
  adminOrgs: (params: Record<string, unknown>) => ['admin', 'organizations', params] as const,
};
